
---
title: "Projects"
---

1. Spatial Zero-Inflated Beta Distribution Regression Modeling by [Andriëtte Bekker](Researchers.qmd#abekker)
1. A Robust variance inflated spatial regression model for proportions by [Andriëtte Bekker](Researchers.qmd#abekker)
1. Atypical value plays hide and seek in stack-loss data by [Andriëtte Bekker](Researchers.qmd#abekker)
1. Anomalies observations in sports data by [Andriëtte Bekker](Researchers.qmd#abekker)
1. Sequential optimisation strategy for factorial designs using partitioned factor screening and D-optimal design approaches by [Lyson Chaka](Researchers.qmd#lchaka)
1. Sequential optimisation strategy for factorial designs: A partitioned factor screening and I-optimal design approach by [Lyson Chaka](Researchers.qmd#lchaka)
1. An enhanced MEWMA classifier using supervised machine learning models by [Lyson Chaka](Researchers.qmd#lchaka)
1. One class-MLP-based Adaptive MEWMA scheme using linear support vector regression by [Lyson Chaka](Researchers.qmd#lchaka)
1. The long term educational impact of associative learning by [Loina Coetser](Researchers.qmd#lcoetser)
1. Develop a Strategic Instruction Model (SIM strategies) to promote effective associative learning by [Loina Coetser](Researchers.qmd#lcoetser)
1. Ordinal Logistic Regression for Categorised Mathematics Achievement Using TIMSS Data by [Gretel Crafford](Researchers.qmd#gcrafford)
1. Multinomial Logistic Regression for Categorised Mathematics Achievement Using TIMSS Data by [Gretel Crafford](Researchers.qmd#gcrafford)
1. Modeling sport count data by [Rene Ehlers](Researchers.qmd#rehlers)
1. Propensity score methods for local test score equating by [Rene Ehlers](Researchers.qmd#rehlers)
1. Spatial modelling of wastewater data in epidemiology (up to 3 students) by [Inger Fabris-Rotelli](Researchers.qmd#ifabris)
1. An R package for spatial lattice data by [Inger Fabris-Rotelli](Researchers.qmd#ifabris)
1. A Monte Carlo Simulation Study of the Vuong Test in Stochastic Frontier Models with Heterogeneous Inefficiency by [Aviwe Gqwaka](Researchers.qmd#agqwaka)
1. Simulation-Based Evaluation of the Vuong Test for Selecting Inefficiency Distributions in Stochastic Frontier Models Using OLS Residual Kurtosis by [Aviwe Gqwaka](Researchers.qmd#agqwaka)
1. Spatial Clustering and Fairness in Regional Data by [Gandhi Jafta](Researchers.qmd#jafta)
1. The Modifiable Areal Unit Problem (MAUP) and Its Impact on Statistical Inference by [Gandhi Jafta](Researchers.qmd#jafta)
1. Detecting Spatial Bias in Predictive Models by [Gandhi Jafta](Researchers.qmd#jafta)
1. ⁠Fairness Metrics for Spatial and Continuous Variables by [Gandhi Jafta](Researchers.qmd#jafta)
1. Model-based clustering of mineral compositions to inform geological
applications by [Frans Kanfer](Researchers.qmd#fkanfer)
1. Data clustering using a modal approach by [Frans Kanfer](Researchers.qmd#fkanfer)
1. Data clustering in the presence of non-typical data (up to 2 students) by [Frans Kanfer](Researchers.qmd#fkanfer)
1. The reliability of OLS regression in large-scale observational data when multicollinearity is present by [Judy Kleyn](Researchers.qmd#jkleyn)
1. Shrinkage versus sparsity in feature selection: Evidence from simulation studies by [Judy Kleyn](Researchers.qmd#jkleyn)
1. Dealing with outliers in regression modelling: OLS versus quantile regression by [Judy Kleyn](Researchers.qmd#jkleyn)
1.	Robust Gaussian mixture modelling using self-paced learning by [Andre Kleynhans](Researchers.qmd#akleyn)
2.	Robust mixture modelling using trimmed likelihood methods by [Andre Kleynhans](Researchers.qmd#akleyn)
3.	Selection of the number of components in trimmed Gaussian mixture models by [Andre Kleynhans](Researchers.qmd#akleyn)
4.	Selection of the number of components in cluster weighted regression models by [Andre Kleynhans](Researchers.qmd#akleyn)
1. A flexible gap-time distribution motivated by ICU readmission data by [Brenda Mac'Oduol](Researchers.qmd#brenda)
1. Mixture parametric models for breast cancer survival times in the METABRIC Cohort by [Brenda Mac'Oduol](Researchers.qmd#brenda)
1. Quantile-based parametric modelling of flare gap times in chronic disease (up to 2 students) by [Brenda Mac'Oduol](Researchers.qmd#brenda)
1. Spatial linear network regression of crime data (up to 2 students) by [Kabelo Mahloromela](Researchers.qmd#kmah)
1. Accounting for spatially varying directional effects in spatial covariance structures (up to 2 students) by [Kabelo Mahloromela](Researchers.qmd#kmah)
1. Spatial data augmentation  (up to 2 students) by [Kabelo Mahloromela](Researchers.qmd#kmah)
1. Survival functions for grouped data on insurance data by [Seite Makgai](Researchers.qmd#seite)
1. The relevance of the inverse Gaussian distribution in insurance and economic data by [Seite Makgai](Researchers.qmd#seite)
1. Directional statistics models for protein angle data by [Seite Makgai](Researchers.qmd#seite)
1. A contaminated regression model for count health data by [Seite Makgai](Researchers.qmd#seite)
1. Optimized SVM-based synthetic multivariate EWMA framework using Genetic Algorithm by [Jean- Claude Malela-Majika](Researchers.qmd#jc)
1. Optimized hybrid GA-SVM-based synthetic multivariate CUSUM framework by [Jean- Claude Malela-Majika](Researchers.qmd#jc)
1. Recurring neural network-based framework for time-series data by [Jean- Claude Malela-Majika](Researchers.qmd#jc)
1. One-class hybrid SVM-CNN -based EWMA monitoring scheme by [Jean- Claude Malela-Majika](Researchers.qmd#jc)
1. A Comparative Analysis of Cluster-Specific and Population-Averaged Approaches for Analysing Correlated Binary Data by [Samuel Manda](Researchers.qmd#smanda)
1. Finite Sample Performance of Bootstrap and Asymptotic Confidence Intervals by [Samuel Manda](Researchers.qmd#smanda)
1. Validity of Statistical Inference Following Data-Driven Model Selection by [Samuel Manda](Researchers.qmd#smanda)
1. Gaussian Mixture Models for Model-Based Clustering: A Simulation Study by [Sollie Millard](Researchers.qmd#smillard) 
1. The Effect of Model Misspecification in Gaussian Mixture Models by [Sollie Millard](Researchers.qmd#smillard) 
1. Determining the Number of Clusters in Gaussian Mixture Models by [Sollie Millard](Researchers.qmd#smillard) 
1. A Comparative Study of k-means, k-medians and k-medoid Clustering by [Sollie Millard](Researchers.qmd#smillard) 
1. Spatial modelling of circular data with an application in criminology (up to 2 students) by [Najmeh Nakhaeirad](Researchers.qmd#najmeh)
1. Circular Control Charts for Anomaly Detection in Wind Direction by [Najmeh Nakhaeirad](Researchers.qmd#najmeh)
1. Mixture modelling of claim data by [Arno Otto](Researchers.qmd#aotto)
1. Modelling outliers in subsurface electrical conductivity data by [Arno Otto](Researchers.qmd#aotto)
1. Modelling extraterrestrial objects impacting Earth's surface by [Arno Otto](Researchers.qmd#aotto)
1. Modelling bounded unemployment insurance benefits by [Jason Pillay](Researchers.qmd#jason)
1. Designing a finite mixture modelling framework for incomplete data based on the regular exponential family by [Jason Pillay](Researchers.qmd#jason)
1. Machine learning in mixtures of regressions with application to environmental economics by [Sphiwe Skhosana](Researchers.qmd#skhosana)
1. Mixtures of linear-circular regressions with application to renewable energy by [Sphiwe Skhosana](Researchers.qmd#skhosana)
1. Spatial interpolation of natural hydrogen H2 by [Ansie Smit](Researchers.qmd#asmit)
1. Optimal spatial sampling design for surface detection of natural hydrogen H2 (1 student) by [Ansie Smit](Researchers.qmd#asmit)
1. Spatial-temporal modelling of hail size using INLA (up to 2 students) by [Ansie Smit](Researchers.qmd#asmit)
1. Spatial-temporal modelling of short-term insurance claims due to precipitation using INLA (up to 2 students) by [Ansie Smit](Researchers.qmd#asmit)
1. A hypothesis test for similarity of spatial data (up to 2 students) by [Rene Stander](Researchers.qmd#rstander)
1. Spatial variable selection (up to 2 students) by [Rene Stander](Researchers.qmd#rstander)
1. Traffic simulation on spatial linear networks (up to 2 students) by [Renate Thiede](Researchers.qmd#rthiede)
1. Simulating spatial linear networks (up to 2 students) by [Renate Thiede](Researchers.qmd#rthiede)
1. Traffic data availability analysis by [Renate Thiede](Researchers.qmd#rthiede)
1. Modelling counts over time: from assumptions to forecasts by [Ané van der Merwe](Researchers.qmd#ane)
1. Modelling spatial dependence under non-normal error structures by [Ané van der Merwe](Researchers.qmd#ane)
1. Disease mapping models by [Janet van Niekerk](Researchers.qmd#jvanniekerk)
1. Bayesian Machine learning by [Janet van Niekerk](Researchers.qmd#jvanniekerk)
1. Non-linear association joint models for clinical trials by [Janet van Niekerk](Researchers.qmd#jvanniekerk)
1. Variational inference for survival data by [Janet van Niekerk](Researchers.qmd#jvanniekerk)
1. Data visualisation in sports analytics by [Paul van Staden](Researchers.qmd#pvanstaden)
1. Analysing outcomes in board and/or online games through randomisation and simulation by [Paul van Staden](Researchers.qmd#pvanstaden)
1. Statistical analysis of bowling partnerships in cricket by [Paul van Staden](Researchers.qmd#pvanstaden)
1. Rating and ranking systems for Strictly Come Dancing and Dancing with the Stars by [Paul van Staden](Researchers.qmd#pvanstaden) 
1. Causal Artificial Intelligence (up to 2 students) by [Albert Whata](Researchers.qmd#awhata)
1. Enhanced support vector machine EWMA chart coupled with swamp particle optimization by [Albert Whata](Researchers.qmd#awhata)
1. Evolutionary CUSUM monitoring scheme integrated with support vector feature selection by [Albert Whata](Researchers.qmd#awhata)
1. Evolutionary support vector machine for improving shift detection in health sciences by [Albert Whata](Researchers.qmd#awhata)

