
---
title: "Researchers"
---

# Prof. A. Bekker {#abekker}

# Dr. L. Chaka {#lchaka}
# Mrs. L.E. Coetser
# Dr. G. Crafford
# Mr. M.S. De Lancey
# Dr. R. Ehlers
# Prof. I.N. Fabris-Rotelli
# Mr. T.J.E. Harris 
# Ms. P.H.G. Jafta
# Prof. F.H.J. Kanfer
# Dr. J. Kleyn {#jkleyn}
My research interest are in shrinkage and regularised methods for statistical models. Please see my webpage [here](https://www.up.ac.za/statistics/dr-judy-kleyn). 

# Mr. A.R. Kleynhans
# Dr. I.A. Maharela	
# Dr. K. Mahloromela	
# Dr. S.L. Makgai	
# Dr. M.J.C. Malela
# Prof. S. Manda {#smanda}

# Prof. S.M. Millard
# Dr. N. Nakhaeirad
# Dr. B.V. Otieno Mac'Oduol
# Dr. A.F. Otto
# Mr. J. Pillay
# Ms. C. Retief
# Dr. S.B. Skhosana	
# Dr. R. Stander
# Dr. R.N. Thiede
# Dr. A. van der Merwe
# Prof. J. van Niekerk {#jvanniekerk}
My research areas are Bayesian methods, Biostatistics, Spatial Statistics and Computational Statistics. Most of my work has been at the intersection between statistical methods and the computing of those methods. I am a developer of three R packages; INLA, INLAjoint and graphpcor.
My Google Scholar is available [here](https://scholar.google.com/citations?user=LVqMNKQAAAAJ&hl=en&oi=ao).
I have projects available but also get excited by your project ideas - so feel free to bring your own!

I have four project spaces available for 2026.

# Dr. P.J. van Staden
# Mr. A. van Wyk
# Mrs. L. Venter
# Dr. A. Whata

